id: 5297dcab1d92478f866182c9f164ac26
title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།།
type: root-commentary
source_metadata:
  work_id: W4CZ301801
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།།
  type: root-commentary
  lang: bo
  root_author: ཞི་བ་ལྷ།
  commentary_author: ཀུན་བཟང་དཔལ་ལྡན།
