id: 4c3212759b4a4d32a5303ede4fc84b4b
initial_creation_type: tei
origin_type: root-commentary
source_metadata:
  id: ''
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།།
  language: bo
  work_id: W4CZ301801
  author: ཞི་བ་ལྷ།
  volume: {}
