id: 6d68bb52befb438e8a1d9c60f791575b
initial_creation_type: tei
origin_type: root-commentary
source_metadata:
  id: ''
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།།
  language: bo
  work_id: W4CZ301801
  author: ཀུན་བཟང་དཔལ་ལྡན།
  volume: {}
